language: node_js
cache: yarn
node_js: node

before_install: cd www
install: yarn
script: yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/docs # We cd'd into www before
  on:
    branch: master
deploy:
  provider: npm
  email: $NPM_DPL_EMAIL
  api_key: $NPM_DPL_TOKEN
  tag: next
  on:
    tags: true